[package]
name = "vga9x16"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
image = { version = "0.25.9", default-features = false, features = ["png"] }
rand = "0.10.0"
rocket = "0.5.1"
